### ISSUE TITLE
Unexpected warning during dispatch simple READ_RESOURCES_PENDING

### ISSUE THREAD

**Issue by jincod** [jmeas/redux-resource#241]
Hi @jmeas 

Thank you for your lib.

I try to dispatch action like this:
```
store.dispatch({
  type: actionTypes.READ_RESOURCES_PENDING,
  resourceName: 'books',
  list: 'mostPopular'
});
```
https://redux-resource.js.org/docs/guides/lists.html#using-lists

But i get error:
` Redux Resource action of type READ_RESOURCES_PENDING was dispatched without a "request", "list," or "resources" array. Without one of these values, Redux Resource cannot track your CRUD operation. You should check your Action Creators. Read more about CRUD Actions at`

What I do wrong?

**Comment by jmeas** [comment]
Hey there, @jincod . Sorry for the trouble! I need to update the warning message here.

In short, a request status **must** be tracked somewhere. There are two places you can track a request's status:

- on resource metadata
- using a named request

In the example you've provided, neither a request nor any resources are specified, so you'll have no way of knowing when the request is pending, failed, succeeded, etc.

If you update this to be:

```js
store.dispatch({
  type: actionTypes.READ_RESOURCES_PENDING,
  resourceName: 'books',
  request: 'getMostPopular',
  list: 'mostPopular'
});
```

then you'll now have request tracking! Sorry about that bad warning message. I'll update that today and get a bug fix out!

Let me know if this helps.

**Comment by jincod** [comment]
@jmeas Thank you for explanation. Everything is clear now.

**Comment by jmeas** [comment]
👌 I'm glad I was able to help!

We're discussing in Slack if there'd be any solid way to provide a default `request` when a `list` is provided. That way, users wouldn't necessarily need to type all of this stuff and come up with names for things. If you have any thoughts for that, we'd be curious to hear 'em!

**Comment by jmeas** [comment]
@jincod, sorry for the delay, but a bug fix release of redux-resource was just published. If you pull down 2.3.1, you should see an updated warning message when a `request` or `resources` is omitted.

Thanks for opening this issue, and sorry again!
