### ISSUE TITLE
Restructure lists to support meta

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#249]
@ianmstew brought up a good use case for list metadata. For instance, determining if a list has been fetched before or not.

Right now, I recommend using a top-level property called `listMeta`. But if we update lists to look more like requests:

```
{
  ids: [ ... ],
  ...metaGoesHere
}
```

then you could add additional metadata right on the list itself.

---

Due to `getResources` abstracting away interactions with the list, this is unlikely to be a hugely breaking change for folks. It would mostly require updating any plugins built around lists to account for the new structure.

**Comment by ianmstew** [comment]
I didn't even think about how nicely `lists` could parallel `requests`!  That's outstanding.

**Comment by jmeas** [comment]
@sprjr @marlonpp @tbranyen what do you all think? Is this worth changing or nah? Also, I'm happy to provide more context if ya need it.

**Comment by tbranyen** [comment]
My comment here would be around defining how the Redux slice store is treated in terms of privateness. Is this space protected structure-wise, is it a major update to the lib when this structure changes, etc?

**Comment by jmeas** [comment]
> Is this space protected structure-wise, is it a major update to the lib when this structure changes, etc?

Great question. I don't intend for it to be private, as I want people to go in there and add additional stuff whenever they need to. So I do think of it as a breaking change when the structure changes.

With that said, given the current structure of lists, it's very unlikely that a structure change here would break anyone's app in practice.

**Comment by jmeas** [comment]
I'm thinking I'll do this as part of v3 a few months from now. Closing for now, though. Feel free to leave comments if you have an opinion here! :v:

**Comment by jmeas** [comment]
Related: #292

**Comment by jmeas** [comment]
@ianmstew , I'm thinking this makes sense to hold off until v4.

The reason is because this is a big breaking change right now due to the fact that there's no API that "masks" accessing lists atm; developers are often digging into the slice directly, i.e.;

```js
var someList = books.lists.myList
````.

In v3, there will be new APIs that will be the recommended way to access lists, which will provide an abstraction over this direct access. Once folks start using those, it will be much easier to make this change in v4 without anyone needing to change their code.

Because of the fact that there is a workaround for this issue right now (storing the meta elsewhere on this slice), I'm classifying this as a low-impact breaking change, which is another reason why I'm fine with holding off until v4.

Going to close this out again as revisit for now, but as always I'm open to comments/thoughts!
