### ISSUE TITLE
Document new features of redux-resource-xhr@3.x

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#280]
You can do some neat things with `redux-resource-xhr@3.x`, but they're not fully documented yet. I should figure out a good place to put that info. Namely, chaining requests to dispatch a single action. The related resources guide has a nice section on "compound actions."

---

I should add an FAQ section about "compound actions" (multiple resource types in one action), which would point to the related resources guide.

---

More generally, I wonder if there should be a "Tips & Tricks" guide somewhere. There are already so many docs...but there's so much more to share!

**Comment by roboxv** [comment]
Hello, @jmeas 

It seems in `3.x` you have to specify request method. Which was specified with some defaults before based on request type (`POST` for `create`, `DELETE` for `delete`, etc).

I'm not exactly sure, if you have forgotten to mention it in migration guide or it's a bug or it's mine misunderstanding.

**Comment by jmeas** [comment]
Good catch, @roboxv . You are correct that this is a breaking change that was unspecified in the migration guide. I'll update that right now! Sorry about that!

**Comment by roboxv** [comment]
I think it's nice to have feature, but not top priority.

Thank you for quick response!

**Comment by jmeas** [comment]
Alright, cool. I’ll keep it in mind, and ask some other users what they think. Thanks again for reporting this :v:

**Comment by jmeas** [comment]
I think the current docs of redux-resource-xhr are pretty good. The `onSucceeded` callback is documented, and the Tips section links out to the Related Resources section.
