### ISSUE TITLE
Reintroduce idAttribute: auto map to the ID key

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#286]
I removed this from `redux-resource@2.0.0` thinking it would make plugin authoring easier, but I don't think it's that big a deal. This option allows you to specify what the ID attribute is for your resources.

i.e.;

```js
// this resource has an `idAttribute` that is `bookId`
{
  bookId: 23
}
```

Configuration:

```js
resourceReducer('books', {
  idAttribute: 'bookId'
});
```

I'd need to make sure that all of the utility functions work, and go through the docs to get a sense of what the updates there would look like.

What do folks think? //cc @marlonpp @sprjr @tbranyen ?

**Comment by marlonpp** [comment]
I really liked that option in the past, since in some cases I need to create a transformData function just to add an `id`.

**Comment by jmeas** [comment]
Unfortunately, `idAttribute` isn't compatible with storing request info in a separate slice. Storing request info in a separate slice is required for a number of other features that I think provide more value.

The problem with `idAttribute` is that in an arbitrary request slice, if an action is dispatched with `n` resource types, how can I find their IDs? The request slice doesn't receive any configuration for other resource types, so it can only line things up if everything uses `id`.

One way around this would be a factory for resources that outputs all of your slices, but that is getting too framework-y for my liking.

---

I understand that this comment may leave you wanting to know more info about that standalone request slice. Leave questions here if you want to know more! For now, I'm going to close this out

**Comment by sprjr** [comment]
Just a random thought, but what if `idAttribute` was only used when receiving new resources - but we enforce that gets transformed to `id`?

That would potentially reduce the transformData usage only when backends cannot / won’t, and would save a map without introducing the complexity in other slices.

Might still not be worth it...

**Comment by jmeas** [comment]
@sprjr , do you mean that we would support an `idAttribute` value that performs the mapping for you? That could work.

**Comment by sprjr** [comment]
Yea, it would only handle translating:

`[{ movieId: ... }]` to `[{ id : ... }]`

Users would maybe be confused that backend resources come in one way, but magically are looked up another way.

They might also be annoyed that they have to re-map those in cases where they post the full object back to the server to make updates...so not sure if we could or would cover that too.

**Comment by jmeas** [comment]
This is a great idea.

> They might also be annoyed that they have to re-map those in cases where they post the full object back to the server to make updates...so not sure if we could or would cover that too.

Good question...we should think more about this. Even if the developer must manually map it back when sending data back, I think mapping it to `id` for them would be appreciated :+1:

**Comment by sprjr** [comment]
Maybe change it to `remoteIdAttribute` or `server...`

To indicate that is only used as like a foreign key when pulling them into resources locally.

**Comment by jmeas** [comment]
I thought of a way to do this. If the `idAttribute` is stored on the resource slice, then that should work :v:

**Comment by jmeas** [comment]
I want to get 3.0 out, and this will require a bit of thought to make sure it works with the long-term plan fo' things. Going to close as revisit for now
