### ISSUE TITLE
React bindings: <Resource /> component

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#290]
I was checking out React Apollo to see what their API is like. They encourage [a HoC approach](https://www.apollographql.com/docs/react/basics/setup.html#in-your-ui), like so:

```jsx
import React, { Component } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

// here we create a query opearation
const MY_QUERY = gql`query { todos { text } }`;

// We then can use the graphql container to pass the query results returned by MY_QUERY
// to a component as a prop (and update them as the results change)
const MyComponentWithData = graphql(MY_QUERY)(props => <div>...</div>);
```

A similar API could be created for Redux Resource. @sprjr thought about something like this awhile back with a `<Resource/>` component. We shelved those discussions temporarily after we had come up with the `getStatus` and `getResources` methods, because those were lower-level tools that let us do what we wanted within `connect`'s `mapStateToProps`.

My initial reaction after reading the Apollo docs is that we start by trying to mimic their API directly.

Imagine something like:

```jsx
import React, { Component } from 'react';
import { resource } from 'react-redux-resource';

const MyComponentWithData = resource(REQUEST)(props => <div>...</div>);
```

The question here is defining what `REQUEST` is. Low-hanging fruit requests would be something like:

```js
{
  resourceName: 'books',
  resources: [24]
}
```

But what about if you need books, authors, and comments? And what about fetching lists based on some input? With GraphQL, mapping a query to a request is straightforward, because the query _defines_ the request. Furthermore, my understanding is that it always defines _a single_ request, so more complex queries don't cause many network requests.

For Redux Resource, we would need some way to map these input queries to what could possibly be _multiple_ HTTP requests that your backend supports. This is a more difficult problem.

It could be that the single-input QUERY approach doesn't work for Redux Resource. A possibly-simpler idea could be:

```jsx
import React, { Component } from 'react';
import { resource } from 'react-redux-resource';
import { fetchBooks, fetchAuthors } from './somewhere';

const REQUESTS = [
  fetchBooks({ searchByName: 'Game of' }),
  fetchAuthors({ id: 24 })
];

const MyComponentWithData = resource(REQUESTS)(props => <div>...</div>);
```

Those methods there would be some common interface that we define, similar-ish to action creators but maybe a little different. Then, the component would receive the data in an array format.

Useful links:

- [graphql HoC source](https://github.com/apollographql/react-apollo/blob/55d06d90d94f1a855a704b9ab386ead104522db3/src/graphql.tsx)
- [graphql HoC docs (reads)](https://www.apollographql.com/docs/react/basics/queries.html)
- [graphql HoC docs (writes)](https://www.apollographql.com/docs/react/basics/mutations.html)

**Comment by sprjr** [comment]
+1000 btw. <3

**Comment by jmeas** [comment]
Just leaving an update...this is almost ready :v:

**Comment by jmeas** [comment]
Closing. This work will be tracked over in the [React bindings repo](https://github.com/jmeas/react-redux-resource).
