### ISSUE TITLE
Flow-type

### ISSUE THREAD

**Issue by VladimirPal** [jmeas/redux-resource#310]
Hi!
Any plans about flow-type?

**Comment by jmeas** [comment]
Hi @VladimirPal ! Thanks for the issue.

I don't use flow, so I don't think I could be the one to add in support. But I'd be happy to merge a PR that makes it easier to use this library with flow.

Thanks again :v:

**Comment by jmeas** [comment]
I am interested in supporting Flow, but I don't have the bandwidth to implement this myself. I'm going to close this issue out, but if anyone comes here and wants to add types for this library, then that would be awesome! Leave a comment here and I'll reopen this :v:
