### ISSUE TITLE
Run script to update contributors

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#317]
@jcrben added himself months ago and I forgot to run the script! Sorry, Ben!

I’ll do this first thing tomorrow

**Comment by jmeas** [comment]
Deployed :v: Sorry for the delay @jcrben :v:

**Comment by jcrben** [comment]
Ha, thanks - looking forward to coming back to this, but it'll probably be a month or so.

**Comment by jmeas** [comment]
No worries, Ben 🙂 Should you find the time to come back I'd love to work with you more! I really appreciate the contributions you've already made :v:
