### ISSUE TITLE
Link to real-world example

### ISSUE THREAD

**Issue by VladimirPal** [jmeas/redux-resource#334]
Hi!
Thank you for the lib, we used it in one of our open-source project:
https://github.com/web-pal/chronos-timetracker
https://github.com/web-pal/chronos-timetracker/blob/master/app/reducers/index.js
It may be useful to add the link to an example section.

**Comment by jmeas** [comment]
Great! I’ll do this! Thanks @VladimirPal ✌️

**Comment by jmeas** [comment]
Done and published to the website (GitHub's caching may take a few minutes to pick it up).
