### ISSUE TITLE
JSON API extension

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#38]
It should have JSON API plugins, such as relationships, per-attr updates, meta, and compound documents, plus JSON API-specific action creators.

I'm thinking there will be two parts: a single plugin, and a new action creators lib.

The plugin handles actions like this:

```js
{
  type: 'CREATE_RESOURCES_SUCCEEDED',
  resourceName: 'books',
  resources: [
    {
      id: 2,
      type: 'books',
      attributes: { ... },
      relationships: { ... },
      meta: { ... }
    }
  ],
  included: [{ ... }, { ... }, { ... }]
}
```

The following will happen:

1. The `meta` for each resource will be put on that resource's metadata in the slice.
2. The attributes will have their updates tracked per-attribute
3. relationships will be tracked on the resource
4. `included` resources will be properly added to their slice

---

The action creators would just format this stuff as needed. For document-level meta, I suppose I'd just place it on the label, but possibly *not* on the resource?

**Comment by jmeas** [comment]
Gonna close as revisit for now

**Comment by jmeas** [comment]
The JSON API extension will have the following features:

- per-attribute update statuses
- relationship info
- meta in actions

although it will work with JSON API out of the box, you can format your data on the client to adhere to JSON API to take advantage of these features. That's what I'm doing and it's 👌

**Comment by jcrben** [comment]
fyi, I'm using an `include` parameter to get the related resources in a single request, and then mapping them over with a function which looks like this:
```
import { map, reduce } from 'lodash';

export const getResourcesWithRelated = (
    state: any,
    resourceName: string
    // depth: number = 1, handle later
) => {
    const resources = state[`${resourceName}`].resources;

    const resultResources = map(resources, (resource: any) => {
        const relationships = Object.keys(resource.relationships);
        let resultResource = reduce(
            relationships,
            (accum, relName) => {
                let relResource;
                if (relName === resourceName) return accum;
                // if (depth !== 0) { // fix recursive case later
                //     relResource = getResourcesWithRelated(state, relName, depth - 1);
                // }
                const relationshipData = resource.relationships[relName].data;
                accum[relName] = !Array.isArray(relationshipData)
                    ? relationshipData
                    : map(relationshipData, data => {
                          const relId = data.id;
                          return {
                              id: data.id,
                              type: data.type,
                              ...state[`${relName}`].resources[relId].attributes
                          };
                      });

                return accum;
            },
            {
                id: resource.id,
                type: resource.type,
                ...resource.attributes
            }
        );

        resultResource.meta = resources[resource.id].meta;
        return resultResource;
    });

    return resultResources;
};
```

**Comment by jmeas** [comment]
@jcrben , I really like where you're going with that. So far, I had been focusing on the action creators/reducer side of things, but I can absolutely see the value in having a super-powered `getResources` along the lines of what you've shared. I think there's an app at work that could benefit from something like that, in fact.

Thanks for sharing that! If you ever add in the depth stuff, you should definitely update that comment :)
